### ISSUE TITLE
Field names for `SteeringVectorTrainingSample` could be misleading?

### ISSUE THREAD

**Issue by dtch1997** [steering-vectors/steering-vectors#16]
Currently, `SteeringVectorTrainingSample` is defined like this:

```
class SteeringVectorTrainingSample(NamedTuple):
    positive_prompt: str
    negative_prompt: str
```

However, `positive_prompt` implies that we're only inputting the prompt without the answer, whereas in CAA we actually input both prompt and answer to the model. Renaming this to, e.g. `positive_str` and `negative_str` might be clearer? 

@chanind curious to hear what you think

**Comment by chanind** [comment]
That sounds reasonable to me. The `SteeringVectorTrainingSample` type isn't officially documented so it should be OK to just change IMO. We also haven't hit 1.0 yet, so it should be OK with a minor version bump.
