### ISSUE TITLE
`PatchOperator` misleadingly named

### ISSUE THREAD

**Issue by dtch1997** [steering-vectors/steering-vectors#19]
In `_create_additive_hook`, the the function signature calls for a `PatchOperator`: 
```
PatchOperator = Callable[[Tensor, Tensor], Tensor]
```

The input is supposed to be the original tensor and a steering vector. 
The actual behaviour as defined by code is for this operator to return a _delta_, which will be added to the original tensor to modify it. 
However, this is not obvious from the name, and the most intuitive interpretation would be to define an operator that directly returns the modified tensor.  

I would like to make this clearer somehow through better naming or documentation

**Comment by chanind** [comment]
What about the name `DeltaOperator` or `PatchDeltaOperator`?

**Comment by dtch1997** [comment]
Sounds good
